[package]
name = "Image_Conversion_API"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24", features = ["png", "jpeg", "gif", "bmp"] }
actix-web = "4.0"
